### PR TITLE
Schema generation

### PR DESCRIPTION
**Pull request by andysturrock**
Hi mate,

Initial version here which sets up the framework for generating JSON-like definitions for the messages.  The thing I cannot find, despite a lot of googling is how to list all the instantiated types of a generic type - ie what all the types of T are for StrictSerialiser<T>.  If you can tell me how to do that I'll finish the rest off.

Thanks,

Andy

### CODE REVIEW

**Comment by andysturrock** [comment]
After asking Krzysz and Pawel the thinking is that it is impossible to find all the types of T in GenericType<T> using `Assembly.load()` as `GetGenericArguments()` needs an instance to find the concrete types of T, and obviously there are no instances at load time.  So Pawel and I agreed to use annotations.

See what you think.

**Comment by drewnoakes** [comment]
Hi Andy,

I think schema comparison and publication are orthogonal to the controlled serialisation and deserialisation that dasher provides. It's also getting closer into functionality specific to a closed source project I used to work on that is not generic enough to be part of this package. I'd like to keep this lib small and focussed on object transportation, but feel free to fork it and take it in a different direction if you feel otherwise.

I still maintain that you don't need any annotations for what you're trying to do. I'd written a tool back in the summer that dumped out all the topics defined in an assembly via reflection. It's in the repo as a project of the main solution. It's not a complete solution, but it's a good starting point. The true challenge is to know which topics (and therefore message schema) an application will actually use at runtime. Again there are elegant solutions to this, but it seems the ship has sailed as far as my contributing to those now.

On a completely unrelated note, I read [this](http://joeduffyblog.com/2015/12/19/safe-native-code/) recently and really enjoyed it. Reckon you might too. It goes into some detail on topics we discussed at the tech fair back earlier in the year.

**Comment by andysturrock** [comment]
Yes I was beginning to think so too.  I don't want to fork Dasher, so I will hoist the schema generation stuff into its own repo under my account.  I think this is suitably useful generally, so I will ensure there is nothing related to any particular specific problem, particularly closed source.

I'll take a look at your reflection stuff.  I think there could be benefits of using annotations as you could put other stuff like descriptions etc into them, but it would be easier to not have to use them.

I think the ship could sail back if it wanted to.  Give me a shout when you are back in the UK.

Thanks for the article.  It's very interesting.  One thing that stood out was:
 If I could do it all over agan, I'd banish RTTI. In 90% of the cases, type discriminated unions or pattern matching are more appropriate solutions anyway.
I think one thing most people don't get about performance of languages like Java and C# is that in certain situations it isn't the actual speed of execution that is the issue, it's the predictablilty.  When I worked on an FX eTrading platform the normal performance of the Java solution was fine.  It was the GC collection pauses that killed us.  Yes you can use techniques like circular buffers etc to eliminate GC as possible but that really limits the freedom of the developers.  In the end we re-wrote it using C++ purely because we could make it deterministic.

Kernel developers will only ever use C I think.  They don't think that exceptions work well (eg C++ exceptions in destructors - definitely broken) and every function should just have one way to return control up the stack.

**Comment by andysturrock** [comment]
I've moved all the schema generation and checking stuff to https://github.com/andysturrock/dasher-schema.

**Pull request closed without merging**
